# Generated by Django 3.2 on 2022-02-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
