# Generated by Django 3.2 on 2022-04-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_lists', '0002_auto_20220412_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='to_do_lists.list'),
        ),
    ]
