# Generated by Django 3.2 on 2022-02-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='clean',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='housing',
            name='heat',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='housing',
            name='water',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
