# Generated by Django 3.2 on 2022-02-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20220209_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housing',
            options={'verbose_name_plural': 'Housing'},
        ),
        migrations.AlterModelOptions(
            name='housingtype',
            options={'verbose_name_plural': 'Housing Type'},
        ),
        migrations.AlterField(
            model_name='housing',
            name='clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='housing',
            name='heat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='housing',
            name='water',
            field=models.BooleanField(default=False),
        ),
    ]
