# Generated by Django 3.2 on 2022-02-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20220209_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('details', models.TextField()),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('housing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.housing')),
            ],
        ),
    ]
