# Generated by Django 3.2 on 2022-02-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housing',
            old_name='clean',
            new_name='tidy',
        ),
    ]
