# Generated by Django 3.2 on 2022-02-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_clean_housing_tidy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housing',
            old_name='type',
            new_name='h_type',
        ),
    ]
